apiVersion: apps/v1
kind: Deployment
metadata:
  name: hep-sre-mini
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hep-sre-mini
  template:
    metadata:
      labels:
        app: hep-sre-mini
    spec:
      serviceAccountName: hep-sre-mini
      containers:
      - name: hep-sre-mini
        image: docker.io/emirozbir/micro-sre:v3
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: llm-credentials
              key: key
---
apiVersion: v1
kind: Service
metadata:
  name: hep-sre-mini
  namespace: monitoring
spec:
  selector:
    app: hep-sre-mini
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080